[config]
transactions = 1000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "jito"
url = "http://64.130.45.18:50051"
kind = "shredstream"

[[endpoint]]
name = "xw_tx_local"
url = "udp://127.0.0.1:62001"
kind = "xw_tx"
