[config]
transactions = 1000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "shreder"
url = "http://64.130.45.98:10040"
x_token = ""
kind = "shreder"

[[endpoint]]
name = "node1-local"
url = "udp://0.0.0.0:9527"
kind = "node1"
