[config]
transactions = 1000
account = "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA"
commitment = "processed"

[[endpoint]]
name = "tx-stream"
url = "udp://0.0.0.0:12003"
kind = "node1"

[[endpoint]]
name = "raw-shred"
url = "udp://0.0.0.0:12000"
kind = "raw_shred"
